[package]

name = "read_filter"
version = "0.1.0"
authors = ["Michael Panciera <michael.panciera.work@gmail.com>"]


[dependencies]
rayon = "0.6.0"
bio = "0.10.0" 
lzw = { git = "https://github.com/nwin/lzw" }
docopt = "0.7.0"
rustc-serialize = "0.3.22"
